name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 31
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_stars: yes
