name: Metrics
on:
  # Schedule updates every 3 days 
  schedule: [{cron: "0 0 */3 * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_stars: yes
          plugin_gists: yes
